### ISSUE TITLE
wagtail 2 compatibility

### ISSUE THREAD

**Issue by grasshoppermouse** [benjaoming/wagtailosm#2]
[wagtailosm/wagtailosm/wagtail_hooks.py](https://github.com/benjaoming/wagtailosm/blob/master/wagtailosm/wagtail_hooks.py)

`from wagtail.wagtailcore import hooks`

Needs to be:

`from wagtail.core import hooks`

**Comment by benjaoming** [comment]
Right, thanks! Did that make it work for you, or is there further breakage?

**Comment by grasshoppermouse** [comment]
That change made it work.

**Comment by benjaoming** [comment]
@grasshoppermouse could you try 0.2 on PyPi, LMK if it works!

**Comment by grasshoppermouse** [comment]
Yep, seems to work fine. Thanks for the fast fix!

**Comment by benjaoming** [comment]
You're welcome :)

**Comment by benjaoming** [comment]
Thanks for reporting!
